steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_AR_HOSTNAME}/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_AR_HOSTNAME}/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_AR_HOSTNAME}/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AR_HOSTNAME: asia-northeast1-docker.pkg.dev
  _REPO_NAME: cloud-run-source-deploy
  _SERVICE_NAME: gogatsusai-backend
  _REGION: asia-northeast1
